version: '3.8'
services:
  menu-service:
    build: ./menu-service
    ports:
      - "8081:8080"
  order-service:
    build: ./order-service
    environment:
      - MENU_SERVICE_URL=http://menu-service:8080/api/menu
    ports:
      - "8082:8080"
